services:
 # 백엔드 서비스
 narrativa_backend:
   build: 
     context: ./narrativa_backend
     dockerfile: Dockerfile.local
     args:
       AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
       AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
       AWS_REGION: ${AWS_REGION}
       AWS_DEFAULT_REGION: ${AWS_REGION}
       S3_BUCKET_NAME: ${S3_BUCKET_NAME}
       S3_FILE_KEY: ${S3_FILE_KEYY}
       REACT_APP_URI: ${REACT_APP_URI}
   container_name: narrativa_backend
   ports:
     - "8080:8080"
   expose:
     - "8080"
   env_file:
     - .env
   environment:
     - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
     - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
     - AWS_REGION=${AWS_REGION}
     - AWS_DEFAULT_REGION=${AWS_REGION}
     - S3_BUCKET_NAME=${S3_BUCKET_NAME}
     - S3_FILE_KEY=${S3_FILE_KEYY}
     - SPRING_DATASOURCE_URL=jdbc:mysql://narrativa_mysql:3306/${MYSQL_DATABASE}
     - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
     - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
     - REACT_APP_URI=${REACT_APP_URI}
   networks:
     - narrativa_network
   depends_on:
     narrativa_mysql:
       condition: service_healthy

 # 프론트엔드 서비스
 narrativa_frontend:
   build:
     context: ./narrativa_frontend
     dockerfile: Dockerfile.local
     args:
       REACT_APP_KAKAO_CLIENT_ID: ${REACT_APP_KAKAO_CLIENT_ID}
       REACT_APP_KAKAO_AUTH_CODE_PATH: ${REACT_APP_KAKAO_AUTH_CODE_PATH}
       REACT_APP_KAKAO_REDIRECT_URI: ${REACT_APP_KAKAO_REDIRECT_URI}
       REACT_APP_GOOGLE_CLIENT_ID: ${REACT_APP_GOOGLE_CLIENT_ID}
       REACT_APP_GOOGLE_AUTH_CODE_PATH: ${REACT_APP_GOOGLE_AUTH_CODE_PATH}
       REACT_APP_GOOGLE_REDIRECT_URI: ${REACT_APP_GOOGLE_REDIRECT_URI}
       REACT_APP_GITHUB_CLIENT_ID: ${REACT_APP_GITHUB_CLIENT_ID}
       REACT_APP_GITHUB_AUTH_CODE_PATH: ${REACT_APP_GITHUB_AUTH_CODE_PATH}
       REACT_APP_URI: ${REACT_APP_URI}
       REACT_APP_SPRING_URI: ${REACT_APP_SPRING_URI}
   container_name: narrativa_frontend
   ports:
     - "3010:3010"
   expose:
     - "3010"
   env_file:
     - .env
   environment:
     - REACT_APP_KAKAO_CLIENT_ID=${REACT_APP_KAKAO_CLIENT_ID}
     - REACT_APP_KAKAO_AUTH_CODE_PATH=${REACT_APP_KAKAO_AUTH_CODE_PATH}
     - REACT_APP_KAKAO_REDIRECT_URI=${REACT_APP_KAKAO_REDIRECT_URI}
     - REACT_APP_GOOGLE_CLIENT_ID=${REACT_APP_GOOGLE_CLIENT_ID}
     - REACT_APP_GOOGLE_AUTH_CODE_PATH=${REACT_APP_GOOGLE_AUTH_CODE_PATH}
     - REACT_APP_GOOGLE_REDIRECT_URI=${REACT_APP_GOOGLE_REDIRECT_URI}
     - REACT_APP_GITHUB_CLIENT_ID=${REACT_APP_GITHUB_CLIENT_ID}
     - REACT_APP_GITHUB_AUTH_CODE_PATH=${REACT_APP_GITHUB_AUTH_CODE_PATH}
     - REACT_APP_URI=${REACT_APP_URI}
     - REACT_APP_SPRING_URI=${REACT_APP_SPRING_URI}
   networks:
     - narrativa_network
   depends_on:
     - narrativa_backend

 # 관리자 페이지 서비스
 narrativa_admin:
   build:
     context: ./narrativa_admin
     dockerfile: Dockerfile
   container_name: narrativa_admin
   ports:
     - "3030:3030"
   expose:
     - "3030"
   env_file:
     - .env
   networks:
     - narrativa_network
   depends_on:
     - narrativa_backend

 # 머신러닝 서비스
 narrativa_ml:
   build: 
     context: ./narrativa_ml
   container_name: narrativa_ml
   ports:
     - "8050:8050"
   expose:
     - "8050"
   env_file:
     - .env
   networks:
     - narrativa_network

 # 데이터베이스 서비스
 narrativa_mysql:
   image: mysql:8.0.40
   container_name: narrativa_mysql
   environment:
     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
     MYSQL_DATABASE: ${MYSQL_DATABASE}
     MYSQL_USER: ${MYSQL_USER}
     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
   ports:
     - "3306:3306"
   expose:
     - "3306"
   volumes:
     - ./data:/var/lib/mysql
   networks:
     - narrativa_network
   healthcheck:
     test: ["CMD-SHELL", "mysqladmin ping -h localhost -p${MYSQL_ROOT_PASSWORD}"]
     interval: 10s
     timeout: 5s
     retries: 5

# 네트워크 설정
networks:
 narrativa_network:
   driver: bridge
   ipam:
     config:
       - subnet: 172.20.0.0/16
         gateway: 172.20.0.1

# 볼륨 설정
volumes:
 mysql_data: