CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE}.* TO '${MYSQL_USER}'@'%';
FLUSH PRIVILEGES;

-- 데이터베이스 생성 (없는 경우)
CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE}
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

-- 데이터베이스 선택
USE ${MYSQL_DATABASE};

-- 추가 설정
SET GLOBAL time_zone = '+09:00';
SET time_zone = '+09:00';