name: Daily Submodule Update and Container Refresh

on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-and-refresh:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.ACTION_TOKEN }}

      - name: Update submodules
        shell: powershell
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git submodule foreach --recursive "git pull origin main || git pull origin master"
          git status --porcelain | ForEach-Object {
              Write-Host "Detected changes in submodule: $_"
              git add $_
          }
          if (git diff-index --quiet HEAD --) {
              Write-Host "No changes detected. Skipping commit and push."
          } else {
              git commit -m "chore: update submodules"
              git push origin HEAD
          }

      - name: Stop and remove existing containers
        shell: powershell
        run: |
          if (Test-Path "docker-compose.yml") {
              Write-Host "Stopping and removing existing containers..."
              docker-compose down --remove-orphans
          } else {
              Write-Host "docker-compose.yml not found. Skipping container removal."
          }

      - name: Pull latest images
        shell: powershell
        run: |
          if (Test-Path "docker-compose.yml") {
              Write-Host "Pulling latest Docker images..."
              docker-compose pull
          } else {
              Write-Host "docker-compose.yml not found. Skipping image pull."
          }

      - name: Build and start containers
        shell: powershell
        run: |
          if (Test-Path "docker-compose.yml") {
              Write-Host "Building and starting containers..."
              docker-compose up -d --build
          } else {
              Write-Host "docker-compose.yml not found. Skipping build and start."
          }

      - name: Check container status and logs
        shell: powershell
        run: |
          Start-Sleep -Seconds 30
          Write-Host "Checking Docker container status..."
          docker ps
          if (Test-Path "docker-compose.yml") {
              docker-compose ps
              docker-compose logs --tail=100
          } else {
              Write-Host "docker-compose.yml not found. Skipping logs."
          }

      - name: Clean up old images
        shell: powershell
        run: |
          Write-Host "Cleaning up unused Docker images..."
          docker system prune -f

      - name: Create deployment status file
        if: failure()
        shell: powershell
        run: |
          try {
              $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
              $status = @{
                  timestamp = $timestamp
                  status = "FAILED"
                  repository = $env:GITHUB_REPOSITORY
                  workflow = $env:GITHUB_WORKFLOW
                  runId = $env:GITHUB_RUN_ID
                  runner = $env:COMPUTERNAME
                  errorMessage = "Deployment process failed. Check the workflow logs for details."
              } | ConvertTo-Json -Depth 10

              $statusFile = "deployment_status.json"
              $status | Out-File -FilePath $statusFile -Encoding utf8

              Write-Host "::error::Deployment failed at $timestamp. Status file created: $statusFile"
              Write-Host "Current Docker Status:"
              docker ps -a
              if (Test-Path "docker-compose.yml") {
                  docker-compose ps
              }
          } catch {
              Write-Host "::error::Failed to create deployment status file. Exception: $_"
          }
          exit 1
